---
- hosts: app
  become: yes
  serial: 1

  pre_tasks:
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: "{{ item }}"
      with_items: groups.balancer

  tasks:
    - debug: msg="Deployment would be done here."

  post_tasks:
    - name: Wait for backend to come back up.
      wait_for:
        host: '{{ inventory_hostname }}'
        port: 80
        state: started
        timeout: 60

    - name: Enable the backend server in HAProxy.
      haproxy:
        state: enabled
        host: '{{ inventory_hostname }}'
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: "{{ item }}"
      with_items: groups.balancer
