---
services: docker

branches:
  only:
    - master

env:
  - shell_script: collection.sh

  # Run each test playbook in a separate environment.
  - playbook: deployments.yml
    distro: ubuntu1804
    test_idempotence: false

  # TODO: Not easy to test in CI at this time.
  # - playbook: deployments-balancer.yml
  #   distro: ubuntu1804

  - playbook: deployments-rolling.yml
    distro: ubuntu1804

  - playbook: docker.yml
    distro: ubuntu1604
    test_idempotence: false

  - playbook: docker-hubot.yml
    distro: ubuntu1604
    test_idempotence: false

  - playbook: drupal.yml
    distro: ubuntu1604

  # TODO: Not easy to test in CI at this time.
  # - playbook: dynamic-inventory.yml
  #   distro: ubuntu1604

  - playbook: elk.yml
    distro: ubuntu1804

  - playbook: first-ansible-playbook.yml
    distro: centos7

  - playbook: https-self-signed.yml
    distro: ubuntu1604

  - playbook: https-nginx-proxy.yml
    distro: debian10

  - playbook: includes.yml
    distro: ubuntu1604

  - playbook: jenkins.yml
    distro: ubuntu1604

  # TODO: Not easy to test in CI at this time.
  # - playbook: kubernetes.yml
  #   distro: debian9

  # TODO: Not easy to test in CI at this time.
  # - playbook: lamp-infrastructure.yml
  #   distro: ubuntu1604

  - shell_script: molecule.sh

  - playbook: nodejs.yml
    distro: centos7

  - playbook: nodejs-role.yml
    distro: centos7

  # TODO: Not easy to test in CI at this time.
  # - playbook: orchestration.yml
  #   distro: ubuntu1604

  - playbook: solr.yml
    distro: ubuntu1604

  - playbook: test-plugin.yml
    distro: centos7

script:
  # Use test shim and run playbook if playbook is provided.
  - |
      if [ ! -z "$playbook" ]; then
        # Download test shim.
        wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
        chmod +x ${PWD}/tests/test.sh
        # Run tests.
        ${PWD}/tests/test.sh
      fi

  # Run script directly if script is provided.
  - |
      if [ ! -z "$shell_script" ]; then
        ${PWD}/tests/${shell_script}
      fi
