---
services: docker

env:
  # Run each test playbook in a separate environment.
  - playbook: deployments.yml
    distro: ubuntu1804
    test_idempotence: false


script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
