---
services: docker

env:
  # Run each test playbook in a separate environment.
  - playbook: deployments.yml
    distro: ubuntu1404
    test_idempotence: false

  # TODO: Not easy to test in CI at this time.
  # - playbook: deployments-balancer.yml
  #   distro: ubuntu1404

  - playbook: deployments-rolling.yml
    distro: ubuntu1404

  - playbook: docker.yml
    distro: ubuntu1604
    test_idempotence: false

  - playbook: drupal.yml
    distro: ubuntu1604

  # TODO: Not easy to test in CI at this time.
  # - playbook: dynamic-inventory.yml
  #   distro: ubuntu1604

  - playbook: includes.yml
    distro: ubuntu1604

  # TODO.
  # - playbook: jenkins.yml
  #   distro: ubuntu1604

  # TODO.
  # - playbook: lamp-infrastructure.yml
  #   distro: ubuntu1604

  # TODO.
  # - playbook: nodejs.yml
  #   distro: ubuntu1604

  # TODO.
  # - playbook: nodejs-role.yml
  #   distro: ubuntu1604

  # TODO.
  # - playbook: orchestration.yml
  #   distro: ubuntu1604

  # TODO.
  # - playbook: solr.yml
  #   distro: ubuntu1604

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
