---
- hosts: nodejs-api
  gather_facts: no
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Ensure Node.js API app is present.
      git:
        repo: "{{ app_repository }}"
        version: "{{ app_version }}"
        dest: "{{ app_directory }}"
        accept_hostkey: true
      register: app_updated
      notify: restart forever apps

    - name: Stop all running instances of the app.
      command: "forever stopall"
      when: app_updated.changed

    - name: Ensure Node.js API app dependencies are present.
      npm: "path={{ app_directory }}"
      when: app_updated.changed

    - name: Run Node.js API app tests.
      command: "npm test chdir={{ app_directory }}"
      when: app_updated.changed

    - name: Get list of all running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Ensure Node.js API app is started.
      command: "forever start {{ app_directory }}/app.js"
      when: "forever_list.stdout.find('app.js') == -1"

    - name: Add cron entry to start Node.js API app on reboot.
      cron:
        name: "Start Node.js API app"
        special_time: reboot
        job: "forever start {{ app_directory }}/app.js"

  handlers:
    - name: restart forever apps
      command: "forever restartall"
