---
- hosts: nodejs-api
  become: yes

  vars:
    npm_config_prefix: "/usr"
    nodejs_npm_global_packages:
      - forever
    firewall_allowed_tcp_ports:
      - "22"
      - "8080"

  roles:
    - geerlingguy.firewall
    - geerlingguy.nodejs

  tasks:
    - debug: var=nodejs_install_npm_user