---
- name: Get software for apt repository management.
  apt:
    name:
      - python-apt
      - python-pycurl
    state: present

- name: Add ondrej repository for later versions of PHP.
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: "Install Apache, MySQL, PHP, and other dependencies."
  apt:
    name:
      - acl
      - git
      - curl
      - unzip
      - sendmail
      - apache2
      - php7.4-common
      - php7.4-cli
      - php7.4-dev
      - php7.4-gd
      - php7.4-curl
      - php7.4-json
      - php7.4-opcache
      - php7.4-xml
      - php7.4-mbstring
      - php7.4-pdo
      - php7.4-mysql
      - php7.4-apcu
      - libpcre3-dev
      - libapache2-mod-php7.4
      - python3-mysqldb
      - mysql-server
    state: present

- name: Disable the firewall (since this is for local dev only).
  service: name=ufw state=stopped

- name: "Start Apache, MySQL, and PHP."
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2
    - mysql
