---
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: Move Composer into globally-accessible location.
  command: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer