---
- hosts: lamp_www
  become: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached

  tasks:
    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy our fancy server-specific home page.
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php

    - name: Ensure required SELinux dependency is installed.
      package:
        name: libsemanage-python
        state: present

    - name: Configure SELinux to allow HTTPD connections.
      seboolean:
        name: "{{ item }}"
        state: true
        persistent: true
      with_items:
        - httpd_can_network_connect_db
        - httpd_can_network_memcache
      when: ansible_selinux.status == 'enabled'
