---
- hosts: k8s
  become: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Copy Flannel manifest tailored for Vagrant.
      copy:
        src: files/manifests/kube-system/kube-flannel-vagrant.yml
        dest: "~/kube-flannel-vagrant.yml"

  roles:
    - role: geerlingguy.swap
      tags: ['swap', 'kubernetes']

    - role: geerlingguy.docker
      tags: ['docker']

    - role: geerlingguy.kubernetes
      tags: ['kubernetes']
